# nexussentry/agents/fixer.py
"""
Agent C — The Fixer
━━━━━━━━━━━━━━━━━━━
Executes the Architect's plan using Claw Code's Rust sandbox.
The "hands" of the swarm — this is where code actually gets modified.

When Claw Code is unavailable, uses LLM to generate real working code files
and saves them to the output/ directory.

Role in the swarm: Executor. The one who does the work.
Provider preference: auto (uses whatever's available)
"""

import json
import os
import re
import logging
from datetime import datetime
from pathlib import Path

from nexussentry.adapters.claw_bridge import ClawBridge
from nexussentry.providers.llm_provider import get_provider

logger = logging.getLogger("Fixer")

FIXER_SYSTEM = """You are a precise code execution engine. Given a technical plan, 
simulate its execution and report what changes would be made.

Respond ONLY with valid JSON:
{
  "success": true/false,
  "output": "description of what was done",
  "files_modified": ["file1.py", ...],
  "commands_run": ["cmd1", ...],
  "errors": []
}"""

# Dedicated prompt for generating individual code files
CODE_GEN_SYSTEM = """You are an expert full-stack developer. You write COMPLETE, WORKING,
PRODUCTION-QUALITY code. You never write placeholder comments like "add code here" or "TODO".
Every file you generate must be fully functional and ready to run.

CRITICAL RULES:
- HTML files: Generate a COMPLETE STANDALONE page with <!DOCTYPE html>, <head>, <body>.
  Include ALL CSS inline in a <style> tag. Include ALL JavaScript inline in a <script> tag.
  The HTML MUST work when opened directly in a browser by double-clicking — NO server needed.
  DO NOT use template engines (no Jinja2 {{ }}, no EJS, no Handlebars).
  DO NOT use placeholder values. Use JavaScript for dynamic behavior.
  Make it look PROFESSIONAL with modern CSS (gradients, shadows, animations, Google Fonts).
- CSS files: Generate complete stylesheets with modern design patterns.
- Python files: Generate complete modules with all imports, classes, functions, error handling.
  Include if __name__ == "__main__" block for testing where appropriate.
- JavaScript files: Generate complete scripts with event listeners, DOM manipulation, etc.
- Always include comments explaining the code.
- Never skip any implementation. Write EVERY function body completely.

You MUST respond with ONLY the raw source code for the file. No markdown, no backticks,
no explanations before or after. Just the pure source code."""

# Project root (DevMatrix/)
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


class FixerAgent:
    """Executes the Architect's plan — generates real code files and saves them."""

    def __init__(self):
        self.claw = ClawBridge()
        self.tasks_executed = 0
        self.output_dir = PROJECT_ROOT / "output"

    def _get_session_dir(self) -> Path:
        """Create a timestamped session directory inside output/."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        session_dir = self.output_dir / f"session_{timestamp}"
        session_dir.mkdir(parents=True, exist_ok=True)
        return session_dir

    def _save_generated_files(self, generated_files: dict, task_desc: str,
                               session_dir: Path) -> list:
        """Save LLM-generated code files to disk."""
        saved_files = []

        if not generated_files:
            return saved_files

        for filename, content in generated_files.items():
            try:
                # Sanitize filename (prevent path traversal, remove invalid chars)
                safe_name = re.sub(r'[<>:"|?*]', '_', Path(filename).name)
                if not safe_name:
                    continue

                filepath = session_dir / safe_name
                filepath.write_text(content, encoding="utf-8")
                saved_files.append(str(filepath))
                print(f"    💾 Saved: {filepath.relative_to(PROJECT_ROOT)}")
            except Exception as e:
                logger.warning(f"Could not save {filename}: {e}")

        # Also save a README with task info
        readme_path = session_dir / "README.md"
        if not readme_path.exists():
            readme_content = f"""# NexusSentry Generated Output

**Task:** {task_desc}
**Generated at:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Files generated:** {len(saved_files)}

## Files
{chr(10).join(f'- `{Path(f).name}`' for f in saved_files)}

---
*Generated by NexusSentry Agent Swarm*
"""
            readme_path.write_text(readme_content, encoding="utf-8")

        return saved_files

    def execute(self, plan: dict, tracer=None) -> dict:
        plan_summary = plan.get("plan_summary", "Unknown plan")
        provider = get_provider()
        provider_name = provider.get_provider_for_agent("fixer")

        if tracer:
            tracer.log("Fixer", "execute_start", {
                "plan": plan_summary,
                "provider": provider_name,
                "execution_mode": self.claw.execution_mode,
            })

        mode_badge = f" [{self.claw.execution_mode.upper()}]"
        print(f"\n🔧 Fixer executing{mode_badge}...")

        try:
            # Build a detailed prompt from the Architect's plan
            task = f"""
Execute this technical plan:

PLAN: {plan_summary}
APPROACH: {plan.get('approach', 'Direct implementation')}

Files to read first: {', '.join(plan.get('files_to_read', []))}
Files to modify: {', '.join(plan.get('files_to_modify', []))}
Commands to run: {'; '.join(plan.get('commands_to_run', []))}
Success criteria: {plan.get('success_criteria', 'Task completes without errors')}

Be careful. Report every change. If something fails, report it honestly.
"""
            result = self.claw.run(
                task=task,
                context={"safety_mode": "sandboxed", "dry_run": "false"}
            )

            # If Claw returned a simulated result, enhance it with LLM reasoning
            if result.get("execution_mode") == "simulated":
                result = self._llm_enhanced_execution(plan, result, provider)

            # ── Generate and save real code files ──
            generated_files = result.get("generated_files", {})

            # Always generate real code files via dedicated per-file LLM calls
            if not generated_files and result.get("success"):
                files_to_modify = plan.get("files_to_modify", [])
                if files_to_modify:
                    generated_files = self._generate_code_files(plan, provider)

            if generated_files:
                session_dir = self._get_session_dir()
                saved = self._save_generated_files(
                    generated_files, plan_summary, session_dir
                )
                result["saved_to"] = str(session_dir)
                result["saved_files"] = saved
                if saved:
                    print(f"    📂 Output saved to: output/{session_dir.name}/")

            self.tasks_executed += 1
            status = "✅ Success" if result.get("success") else "❌ Failed"
            elapsed = result.get("elapsed", "?")
            exec_mode = result.get("execution_mode", "unknown").upper()
            print(f"🔧 Fixer result: {status} [{exec_mode}] ({elapsed}s) via {provider_name}")

            if tracer:
                tracer.log("Fixer", "execute_done", {
                    **{k: v for k, v in result.items() if k != "generated_files"},
                    "provider": provider_name,
                    "execution_mode": result.get("execution_mode", "unknown"),
                    "files_saved": len(result.get("saved_files", [])),
                })

            return result

        except Exception as e:
            logger.error(f"Fixer execution failed: {e}")
            error_result = {
                "success": False,
                "error": str(e),
                "output": "Fixer execution encountered an error",
                "files_modified": [],
                "commands_run": [],
                "elapsed": 0,
                "execution_mode": "unavailable",
            }
            print(f"🔧 Fixer result: ❌ Error [UNAVAILABLE] — {e}")
            if tracer:
                tracer.log("Fixer", "execute_error", {"error": str(e), "execution_mode": "unavailable"})
            return error_result

    def _llm_enhanced_execution(self, plan: dict, mock_result: dict,
                                 provider) -> dict:
        """Use LLM to simulate the execution result (not code generation)."""
        try:
            raw = provider.chat(
                system=FIXER_SYSTEM,
                user_msg=f"""Simulate executing this plan:
Plan: {plan.get('plan_summary', '')}
Approach: {plan.get('approach', '')}
Files: {', '.join(plan.get('files_to_modify', []))}
Commands: {'; '.join(plan.get('commands_to_run', []))}""",
                max_tokens=800,
                agent_name="fixer"
            )

            # Try to parse JSON from response
            try:
                result = json.loads(raw)
            except json.JSONDecodeError:
                json_match = re.search(r'\{.*\}', raw, re.DOTALL)
                if json_match:
                    try:
                        result = json.loads(json_match.group(0))
                    except json.JSONDecodeError:
                        result = mock_result
                else:
                    result = mock_result

            result["elapsed"] = mock_result.get("elapsed", 1.5)
            result["execution_mode"] = "simulated"
            result.setdefault("success", True)
            result.setdefault("files_modified", [])
            result.setdefault("commands_run", [])
            result.setdefault("errors", [])
            result.setdefault("generated_files", {})
            return result

        except Exception:
            return mock_result

    def _generate_code_files(self, plan: dict, provider) -> dict:
        """
        Generate REAL, WORKING code for each file — one LLM call per file.
        This ensures each file gets full attention and complete code.
        """
        files_to_modify = plan.get("files_to_modify", [])
        plan_summary = plan.get("plan_summary", "")
        approach = plan.get("approach", "")
        generated_files = {}

        for filename in files_to_modify:
            safe_name = re.sub(r'[<>:"|?*]', '_', Path(filename).name)
            if not safe_name:
                continue

            # Determine file type for targeted prompts
            ext = Path(safe_name).suffix.lower()
            file_type_hints = self._get_file_type_hints(ext)

            prompt = f"""Generate the COMPLETE, WORKING source code for the file: {safe_name}

PROJECT CONTEXT:
- Overall Plan: {plan_summary}
- Approach: {approach}
- All files in this task: {', '.join(files_to_modify)}
- You are generating: {safe_name}

{file_type_hints}

CRITICAL RULES:
1. Write COMPLETE, RUNNABLE code — no placeholders, no "TODO", no "add code here"
2. The file must work standalone when saved and opened/executed
3. Include ALL imports, ALL functions, ALL logic
4. Write production-quality code with error handling
5. Respond with ONLY the raw source code — no markdown backticks, no explanations

Generate the complete source code for {safe_name} now:"""

            try:
                raw_code = provider.chat(
                    system=CODE_GEN_SYSTEM,
                    user_msg=prompt,
                    max_tokens=4000,
                    agent_name="fixer"
                )

                # Clean up the response — strip markdown code blocks if LLM wrapped it
                code = self._clean_code_response(raw_code, ext)

                if code and len(code.strip()) > 20:
                    generated_files[safe_name] = code
                    logger.info(f"Generated {safe_name} ({len(code)} chars)")
                else:
                    logger.warning(f"Generated code for {safe_name} was too short, skipping")

            except Exception as e:
                logger.warning(f"Code generation failed for {safe_name}: {e}")

        return generated_files

    def _get_file_type_hints(self, ext: str) -> str:
        """Return specific instructions based on file type."""
        hints = {
            ".html": """FILE TYPE: HTML
- Generate a COMPLETE, STANDALONE HTML5 page with <!DOCTYPE html>, <html>, <head>, <body>
- The file MUST work when opened directly in a browser (double-click to open)
- DO NOT use any template engines (no Jinja2 {{ }}, no EJS <% %>, no Handlebars)
- DO NOT use any server-side code or placeholders
- Include inline <style> with MODERN, BEAUTIFUL CSS:
  * Use a dark or gradient background (e.g. linear-gradient)
  * Centered card layout with box-shadow and border-radius
  * Glassmorphism effect (backdrop-filter: blur)
  * Modern font from Google Fonts (Inter, Roboto, or Poppins)
  * Smooth hover effects, transitions, and micro-animations
  * Professional color scheme (not plain white background)
  * Responsive design that works on mobile
- Include <script> for ALL interactivity:
  * Form validation with JavaScript
  * CSRF token generation using JavaScript (crypto.randomUUID or Math.random)
  * Show/hide password toggle
  * Loading spinner on submit
  * Error message display
- Use hardcoded demo values where needed (no server calls)
- The page MUST look STUNNING and PREMIUM when opened in a browser""",

            ".css": """FILE TYPE: CSS
- Generate a complete stylesheet with modern design
- Use CSS variables for theming
- Include responsive design with media queries
- Add animations and transitions where appropriate""",

            ".js": """FILE TYPE: JavaScript
- Generate complete, working JavaScript
- Use modern ES6+ syntax (const, let, arrow functions, async/await)
- Include event listeners and DOM manipulation
- Add proper error handling with try/catch""",

            ".py": """FILE TYPE: Python
- Generate a complete Python module
- Include all necessary imports at the top
- Use type hints for function parameters
- Include docstrings for classes and functions
- Add proper error handling with try/except
- Follow PEP 8 style guidelines""",

            ".jsx": """FILE TYPE: React JSX
- Generate a complete React component
- Use functional components with hooks
- Include proper styling (CSS-in-JS or className)
- Add proper prop types or TypeScript annotations""",

            ".ts": """FILE TYPE: TypeScript
- Generate complete TypeScript code with proper types
- Use interfaces and type annotations
- Include proper error handling""",
        }
        return hints.get(ext, f"FILE TYPE: {ext}\n- Generate complete, working code for this file type")

    def _clean_code_response(self, raw: str, ext: str) -> str:
        """Strip markdown wrappers from LLM code responses."""
        code = raw.strip()

        # Remove markdown code block wrappers like ```html ... ``` or ```python ... ```
        # Pattern: starts with ```<lang>\n and ends with ```
        block_match = re.match(
            r'^```(?:html|css|javascript|js|python|py|jsx|tsx|typescript|json|sql|sh|bash)?\s*\n(.*?)```\s*$',
            code,
            re.DOTALL | re.IGNORECASE
        )
        if block_match:
            code = block_match.group(1)

        # Also handle triple backtick at start/end without language tag
        if code.startswith("```") and code.endswith("```"):
            lines = code.split("\n")
            code = "\n".join(lines[1:-1])

        return code.strip()
