"""
Agent D — Integrator
━━━━━━━━━━━━━━━━━━━━
Merges builder outputs into a single coherent artifact set and saves files.
"""

import logging
import re
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("Integrator")

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


class IntegratorAgent:
    """Integrates builder outputs and writes artifacts to output/session_* directories."""

    def __init__(self):
        self.output_dir = PROJECT_ROOT / "output"

    def integrate(self, plan: dict, builder_result: dict, tracer=None) -> dict:
        reports = builder_result.get("builder_reports", [])
        merged_files = {}
        conflicts = []
        summaries = []

        if tracer:
            tracer.log("Integrator", "integrate_start", {
                "builders_used": len(reports),
            })

        for report in reports:
            summaries.append(report.get("output", "").strip())
            for filename, content in report.get("generated_files", {}).items():
                if filename in merged_files and merged_files[filename] != content:
                    conflicts.append(filename)
                    if len(content) >= len(merged_files[filename]):
                        merged_files[filename] = content
                else:
                    merged_files[filename] = content

        if not reports:
            merged_files.update(builder_result.get("generated_files", {}))

        integrator_summary = " ".join(part for part in summaries if part)
        if conflicts:
            integrator_summary = (
                f"Integrated builder outputs with conflicts resolved for: {', '.join(sorted(set(conflicts)))}. "
                f"{integrator_summary}".strip()
            )
        elif not integrator_summary:
            integrator_summary = "Integrated builder outputs successfully."

        session_dir, saved_files = self._save_generated_files(
            merged_files,
            plan.get("plan_summary", "Unknown task"),
        )

        result = {
            "generated_files": merged_files,
            "integrator_summary": integrator_summary,
            "integration_conflicts": sorted(set(conflicts)),
            "saved_to": str(session_dir) if session_dir else "",
            "saved_files": saved_files,
        }

        if tracer:
            tracer.log("Integrator", "integrate_done", {
                "files_saved": len(saved_files),
                "integration_conflicts": result["integration_conflicts"],
            })

        return result

    def _save_generated_files(self, generated_files: dict, task_desc: str):
        if not generated_files:
            return None, []

        session_dir = self._get_session_dir()
        saved_files = []

        for filename, content in generated_files.items():
            try:
                safe_name = re.sub(r'[<>:"|?*]', '_', Path(filename).name)
                if not safe_name:
                    continue

                path = session_dir / safe_name
                path.write_text(content, encoding="utf-8")
                saved_files.append(str(path))
            except Exception as exc:
                logger.warning("Could not save %s: %s", filename, exc)

        readme_path = session_dir / "README.md"
        if not readme_path.exists():
            readme_path.write_text(
                f"""# NexusSentry Generated Output

**Task:** {task_desc}
**Generated at:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Files generated:** {len(saved_files)}

## Files
{chr(10).join(f'- `{Path(f).name}`' for f in saved_files)}

---
*Generated by NexusSentry Agent Swarm*
""",
                encoding="utf-8",
            )

        return session_dir, saved_files

    def _get_session_dir(self) -> Path:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        session_dir = self.output_dir / f"session_{timestamp}"
        session_dir.mkdir(parents=True, exist_ok=True)
        return session_dir
